# Generated by Django 5.0.6 on 2024-11-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='published_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
